<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://controller.fmea8d.com.br" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://controller.fmea8d.com.br" xmlns:intf="http://controller.fmea8d.com.br" xmlns:tns1="http://event.faces.javax" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://controller.fmea8d.com.br" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://event.faces.javax"/>
   <element name="listActionListener">
    <complexType>
     <sequence>
      <element name="event" type="xsd:anyType"/>
     </sequence>
    </complexType>
   </element>
   <element name="listActionListenerResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="listActionListenerRequest">

      <wsdl:part element="impl:listActionListener" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="listActionListenerResponse">

      <wsdl:part element="impl:listActionListenerResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="EquipamentoController">

      <wsdl:operation name="listActionListener">

         <wsdl:input message="impl:listActionListenerRequest" name="listActionListenerRequest">

       </wsdl:input>

         <wsdl:output message="impl:listActionListenerResponse" name="listActionListenerResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="EquipamentoControllerSoapBinding" type="impl:EquipamentoController">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="listActionListener">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="listActionListenerRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="listActionListenerResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="EquipamentoControllerService">

      <wsdl:port binding="impl:EquipamentoControllerSoapBinding" name="EquipamentoController">

         <wsdlsoap:address location="http://localhost/consultorio/services/EquipamentoController"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
